name: vuepress-build-check-deploy

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/vuepress-build-check-deploy.yml
      - docs/**
      - .markdownlint.yml
      - .spelling
      - package.json
      - package-lock.json
  push:
    branches:
      - master
    paths:
      - .github/workflows/vuepress-build-check-deploy.yml
      - docs/**
      - .markdownlint.yml
      - .spelling
      - package.json
      - package-lock.json

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          exclude: |
            CHANGELOG.md

  markdown-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck

      - name: Run mdspell
        run: find . -type f \( -name "*.md" ! -name "CHANGELOG.md" \) -print0 | xargs -0 --max-args=1 --verbose mdspell --ignore-numbers --ignore-acronyms --report --en-gb

  vuepress-build-check-deploy:
    runs-on: ubuntu-latest
    needs:
      - markdownlint-check
      - markdown-spell-check
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build VuePress site
        run: npm run docs:build

      - name: Install VuePress and build the document
        run: |
          cp LICENSE docs/.vuepress/dist
          sed -e "s@(part-@(https://github.com/${{ github.repository }}/tree/master/docs/part-@" -e 's@.\/.vuepress\/public\/@./@' docs/README.md > docs/.vuepress/dist/README.md

      - name: Check broken links
        env:
          INPUT_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          INPUT_PAGES_PATH: .
          INPUT_CMD_PARAMS: --buffer-size=8192 --max-connections=10 --color=always --skip-tls-verification --exclude=(mylabs.dev|https://github.com/.*/edit/)
        run: |
          if git ls-remote --heads origin gh-pages | grep gh-pages ; then
            ln -s docs/.vuepress/dist ${{ github.event.repository.name }}
            wget -qO- https://raw.githubusercontent.com/ruzickap/action-my-broken-link-checker/v2/entrypoint.sh | bash
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          force_orphan: true
